trigger:
  branches:
    include:
      - master
      - develop

jobs:
  - job: buildAndUnitTest
    displayName: Build and run unit tests on

    strategy:
      matrix:
        Linux:
          imageName: "ubuntu-latest"
          isPrimaryStrategy: true
        MacOs:
          imageName: "macOs-latest"
        Windows:
          imageName: "windows-latest"

    pool:
      vmImage: "$(imageName)"

    variables:
      isMaster: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]

    steps:
      - task: UseNode@1
        displayName: "Install Node.js"
        inputs:
          version: "14.3.0"
        continueOnError: false

      - task: CmdLine@2
        displayName: "Install Dependencies"
        inputs:
          script: |
            npm ci
        continueOnError: false

      - task: CmdLine@2
        displayName: "Build Project"
        inputs:
          script: |
            npm run build
        continueOnError: false

      - task: CmdLine@2
        displayName: "Test Project"
        inputs:
          script: |
            npm run coverage
        continueOnError: false

      - task: PublishCodeCoverageResults@1
        displayName: "Publish Coverage Results"
        condition: and(succeeded(), variables.isPrimaryStrategy, variables.isMaster)
        inputs:
          codeCoverageTool: "Cobertura"
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/**/coverage/cobertura-coverage.xml"
          reportDirectory: "$(System.DefaultWorkingDirectory)/**/coverage"
        continueOnError: false

      - task: CmdLine@2
        displayName: "Generate Docs"
        condition: and(succeeded(), variables.isPrimaryStrategy, variables.isMaster)
        inputs:
          script: |
            npm run docs
        continueOnError: false

      - task: PublishPipelineArtifact@1
        displayName: "Publish Docs"
        condition: and(succeeded(), variables.isPrimaryStrategy, variables.isMaster)
        inputs:
          targetPath: "$(System.DefaultWorkingDirectory)/docs"
          artifact: "Types Docs"
          publishLocation: "pipeline"
        continueOnError: false
