name: Build and Test

on:
  pull_request:
    branches:
      - master
      - develop

jobs:
  buildAndTest:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.3
        uses: actions/setup-node@v2
        with:
          node-version: 14.3

      - run: npm ci
      - run: npm run build
      - run: npm run coverage --ci

      - name: Codecov
        uses: codecov/codecov-action@v1.3.2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: coverage
